### ISSUE TITLE
Initialize led pins to low

### ISSUE THREAD

**Issue by Davide-sd** [google/OctoPrint-LEDStripControl#11]
Hello,

Looking at the code it appears the pins are initialize to HIGH. When I reboot my Raspberry and turn on the PSU, the light will be on. I would like them to be off, after all I need light only when it's dark. 

Is it possible to add an option in the settings to let users decide wether they want the ligths on or off after a raspberry boot?

**Comment by Muralha** [comment]
@Davide-sd 
please check my branch.

**Comment by precision** [comment]
#16 should have support for this
