### ISSUE TITLE
Setup?

### ISSUE THREAD

**Issue by pokerpilot1994** [google/OctoPrint-LEDStripControl#12]
New to Octopi, is there a guide on how to set this up. Im just getting all white lights all the time. Never turns off after print is done. Also I think it would be really cool if you can choose colors based on a color wheel or pallet in the plugins.

**Comment by precision** [comment]
The plugin doesn't do any handling of automatic on/off/status.  You need to insert the proper GCODE into your start/stop/tool change scripts just like you would if you were using the built in LED support in Marlin.
