### ISSUE TITLE
Additional GPIO control

### ISSUE THREAD

**Issue by jcsntoll** [google/OctoPrint-LEDStripControl#13]
Any chance we can get more than just three control points?
My MOSFET board has four mosfets for example.. 
Might be nice to control a fan, or other accessory.
Maybe offer 4-6 GPIO points?  
I dont mind having to string them all in M150

**Comment by precision** [comment]
I just pushed 0.3.x to the tree.  This has support for RGBW LED strips.  You should be able to use M150 W<PWM> to turn control your 4th mosfet after configuring it.
