### ISSUE TITLE
Cabling + Compatibility Ender 3

### ISSUE THREAD

**Issue by pika28** [google/OctoPrint-LEDStripControl#24]
Hello,

- Does it work with the Ender 3 in the original configuration?-
- Where should I enter this command line : "usermod -a -G gpio pi" ?

My biggest problem is the wiring hardware part of the led. How to wire a RGB 5050 LED strip? I have 4 solder contacts: 12V, RED, GREEN and BLUE.

Bests Regards

**Comment by precision** [comment]
LEDStripControl works via LEDs connected to a Raspberry Pi / SBC's GPIO pins.  It has nothing to do with the printer itself.

**Comment by pika28** [comment]
No need for a controller? I directly cable 12V, R, G and B on the pins of the PI? There is no 12V in the PI ...

**Comment by precision** [comment]
You will need some kind of Mosfet/Relay to switch the power for LEDs.  The GPIOs on a Pi are not 12v compliant (or even 5V).  I've linked a decent tutorial below.

https://dordnung.de/raspberrypi-ledstrip/

**Comment by pika28** [comment]
A great tutorial indeed! There is no module ready for use? I do not have the hardware to create a print circuit.

**Comment by precision** [comment]
I use a board a friend designed.  You could have OSHPark make the PCB and solder up the components.

https://github.com/thatch/step_down_led_board/tree/v1.x

**Comment by pika28** [comment]
I use Google translation to understand you. I do not speak English. if I understand correctly, this card comes connect from the top of the pi? it is this card that feeds the pi blow, no longer need its power?

**Comment by pika28** [comment]
I am not used to this site. I find a photo of the PCB but can we find the list of components? How do we go from the website to the online order? Sorry for all these questions

----- Mail original -----
De: "Uriah Welcome" <notifications@github.com>
À: "google/OctoPrint-LEDStripControl" <OctoPrint-LEDStripControl@noreply.github.com>
Cc: "pika28" <pika28@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Mardi 15 Janvier 2019 21:43:06
Objet: Re: [google/OctoPrint-LEDStripControl] Cabling + Compatibility Ender 3 (#24)



I use a board a friend designed. You could have OSHPark make the PCB and solder up the components. 

https://github.com/thatch/step_down_led_board/tree/v1.x

**Comment by precision** [comment]
I've asked my friend for a bill of materials.  If I remember correct we just used random components we found lying around in the shop. 

But if I were you, I'd just breadboard/perfboard up the schematic in the URL I linked previously.   It is super simple, just some mosfets, a barrel connector, and some wires.

**Comment by pika28** [comment]
do you confirm that this system allows to feed the pi without passing through the micro usb port with 12v to 24v?

M. Chauveau Cédric
