### ISSUE TITLE
Just a simple white LED strip

### ISSUE THREAD

**Issue by Pyr3x** [google/OctoPrint-LEDStripControl#25]
Any chance we can get a small update to just turn a simple white LED strip on and off? Thank You!

**Comment by precision** [comment]
You should be able to use it as is with white only strips.  If you only define the GPIO pin for White and use 'M150 W' to turn it on it should work fine.

**Comment by Pyr3x** [comment]
So I tried it but when I check turn on LED at startup they remain off, only when I uncheck it are they on.

**Comment by precision** [comment]
That sounds like your strip/mosfet is NC vs NO.  You may need to change the pins on the mosfet.
