### ISSUE TITLE
Which LED Strips

### ISSUE THREAD

**Issue by danst0** [google/OctoPrint-LEDStripControl#3]
Which LED Strip would be useable? I usually have those with the WS2812b chip. But this is not what is working here?

Daniel

**Comment by precision** [comment]
Correct, WS2812's require special timing and control that I doubt would be possible on a Pi.  This is for controlling simple RGB strips (soon RGBW)  The ones I use are https://www.amazon.com/gp/product/B006LW2NJM

**Comment by ikirt** [comment]
You can use ws281x with the Pi, please see the following site, https://github.com/jgarff/rpi_ws281x
