### ISSUE TITLE
Documentation link not working

### ISSUE THREAD

**Issue by BomSquad** [google/OctoPrint-LEDStripControl#31]
With the check box for "use pigpiod" there is a documentation link that points to http://abyz.co.uk/rpi/pigpio/pigpiod.html this URL appears to be broken as it just dumps you off to http://abyz.co.uk and a search for pigpio or pigpiod returns no results on that page.

**Comment by precision** [comment]
Oops, it looks like the href link was correct, but I typo'd it in the second link.

**Comment by precision** [comment]
The correct link is http://abyz.me.uk/rpi/pigpio/pigpiod.html
