### ISSUE TITLE
Not an actual issue, more of a question.

### ISSUE THREAD

**Issue by SleepyBlueCat** [google/OctoPrint-LEDStripControl#34]
Hey I LOVE the plugin!! Works very good. Here is something I'd like to implement: A loop that shows all colors in the RGB spectrum. Would this be something too implement in your plugin? Like a special m150 command or somthing. Or would this be something to use with a script?

**Comment by precision** [comment]
Thanks, good to hear it is working for you.

I would probably use a post processing script to insert an M150 every N lines (or layers or whatever) of GCODE personally.  To do something similar in the plugin itself we'd have to either preprocess the GCODE or setup a timer to fire every N seconds and swap the colors.  Both of which are fairly nontrivial to implement.
