### ISSUE TITLE
getting the wrong colours 

### ISSUE THREAD

**Issue by nowkillkennys** [google/OctoPrint-LEDStripControl#8]
hello when i type the commands as follows  incorrect colours come up

M150: Set Status LED Color - Use R-U-B for R-G-B
M150 R255       ; Turn LED red (blue)
M150 R255 U127  ; Turn LED orange
M150            ; Turn LED off
M150 R U B      ; Turn LED white
I ALSO GET PURPLE AND yellow  im using 33 for red 32 for green 12 blue

**Comment by precision** [comment]
What colors do you get if you do each of the following?

```
M150 R
M150 U
M150 B
```

**Comment by precision** [comment]
No response, please reopen if you're still having this issue.
